[package]
name = "rust_proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
systemd-journal-logger = "0.7.0"
simple_logger = "4.0.0"
